### ISSUE TITLE
[Arch 社区评审][代码审计] 低概率情况下可能会造成命令执行

### ISSUE THREAD

**Issue by RicterZ** [cuihaoleo/nvnotifier#1]
用了 pickle 库，在一些配置不当的情况下可以造成命令执行。
虽然概率很小小小小，但是仍然会有可能，所以酌情扣一点点点分（0.5）。

另，可以用更安全的 json 来实现，尽量少用 pickle？

漏洞复现，在能控制到 archcn.db 的情况下：
![image](https://cloud.githubusercontent.com/assets/5282759/9422334/15e8466a-48c2-11e5-918c-f4a7319b935b.png)

![image](https://cloud.githubusercontent.com/assets/5282759/9422336/2837d394-48c2-11e5-968f-abc1a1d262e6.png)

**Comment by RicterZ** [comment]
另外一个比较可能的情况是这样：
- 某台服务器开启了 PHP 的安全模式，不能执行命令
- 服务器的权限是用户权限，也就是能控制到 user 目录
- 服务器开启了计划任务定时执行 nvnotifier

利用方法是替换掉 archcn.db 后，即可等待反弹一个 cmdshell。

**Comment by cuihaoleo** [comment]
lilac 也有这个洞洞哦。
